version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/iac/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/iac/terraform/oci"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/iac/terraform/gcp"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/iac/terraform/aws"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/iac/terraform/cloudflare"
    schedule:
      interval: "weekly"
